### ISSUE TITLE
Viewed Products Cookie

### ISSUE THREAD

**Issue by gety9** [clockworkgeek/Magento-Guest-Cookies#4]
Daniel, hi

At what moment Viewed Products Cookie is created?
and are there any required settings other than [this](https://puu.sh/zvzhV/db5b67c623.png)?

I've supposed it should be created when vising product page. But it's not created.

On the other side cart cookies is working as expected and is created when products are added to cart.

Trying to understand what can be the reason. We are using bundle products (not simple ones) - can it be the reason?

UPDATE: Seems like viewed products looking at report_viewed_product_index table, and i think we have it disabled.

**Comment by clockworkgeek** [comment]
It should happen just as you suppose.  The customer cannot be logged in, because this is for guests only.  Do you have the viewed products block visible?  Then the cookie should be written whenever that has any content and updated on every page thereafter.  The type of product doesn't matter as far as I know.

**Comment by gety9** [comment]
@clockworkgeek 

thank you for clarification. I think it's cause our report_viewed_product_index table is not updated
(seems like we disabled reporting) - will try to re-enable it and see if it works.

**Comment by clockworkgeek** [comment]
That could definitely be a factor.

**Comment by gety9** [comment]
Thank you, will close the issue.
